---
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - task

Metrics/ClassLength:
  Exclude:
    - lib/telegram/bot/api/endpoints.rb
    - lib/telegram/bot/types/message.rb
    - rakelib/builders/type_builder.rb
    - rakelib/parsers/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - rakelib/parsers/**/*

Metrics/AbcSize:
  Exclude:
    - rakelib/parsers/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - rakelib/parsers/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - rakelib/parsers/**/*

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
