---
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - task

Metrics/ClassLength:
  Exclude:
    - lib/telegram/bot/api/endpoints.rb
    - lib/telegram/bot/types/message.rb
    - rakelib/docs_parsers/methods_parser.rb
    - rakelib/docs_parsers/types_parser.rb

Metrics/MethodLength:
  Exclude:
    - rakelib/docs_parsers/methods_parser.rb
    - rakelib/docs_parsers/types_parser.rb
    - spec/**/*

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
