require 'virtus'
require 'logger'
require 'json'

require 'telegram/bot/types'
require 'telegram/bot/exceptions'
require 'telegram/bot/api'
require 'telegram/bot/null_logger'
require 'telegram/bot/client'
require 'telegram/bot/version'
