require 'httmultiparty'
require 'persistent_httparty'
require 'virtus'

require 'telegram/bot/types'
require 'telegram/bot/exceptions'
require 'telegram/bot/api'
require 'telegram/bot/null_logger'
require 'telegram/bot/client'
require 'telegram/bot/scheduler'
require 'telegram/bot/version'
